language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
before_install:
- echo $GPG_KEY > tmp.txt && gpg --batch --passphrase-fd 3 3<tmp.txt secret.gpg.gpg
script: mvn deploy --settings settings.xml -Prelease
env:
  global:
  # SONATYPE_USERNAME
  - secure: amVdEJSMOwolPxTRgl9j3MjFEU590Kk/jS2YuwopZ1g27+tvoVfzzGBHqMlOUlloAtHcpl//0zozb7UqzD0H2xVIvBzPMFFUeAkzpSCDQf80JoTbLIgIpRw53veqkV/+ZBEdaaUSqeEzXFelAPrQQWjCZSEKXxY0BarsfwVJP0g=
  # SONATYPE_PASSWORD
  - secure: QboF5vWCsTw5XKalWGuiZhd+W+86ai3462IWKQx6mhpGEZ0JfMtzPGpF/RyMYAIdWo725eaaBt8o679D+5/5MyqNMfc4WYTBnwNMM2T8UNreTe7z+N6hh8P66AcwsrsUDWdxOytD0zAIZ7jdBq7NcJaz3Sqzx7eq148X9fCQBsA=
  # GPG_PASSPHRASE
  - secure: g/Y/sL8Bd0Fuj4KIWfv6QJBF77lhKE2mUNvRODbsgkd7AZcuzHTtd37Q4/irpM6JTNcLN6/WEOxtjT3ewYWv+Nh3GyltI/FVKpWHXLHcXmGKw+I9JtcB4lnX1TssY/GbCuH7I1hmS99VynSlRCBEoadIAcZRpAp2nFj8U3w3ywI=
  # GPG_KEYID
  - secure: VVqscMgzMkxGrFZb1lLOAHdn9SKD9/1Z1Q9TOhOZUWLM1d08Nc+gDEzjfJ3GgBcPSBtHFgviAo342o9bN1q+nRRwXk6pu0EvZU6Xz/hFQCCaPRF9+9Y4zvcRc+pGjgqZJd8e32XthGfZXrEeNRVkPcOLxW1Gv/Vmx7JxB60JHdM=
  # GPG_KEY
  - secure: W1beTtm20Uz4YubbKmAWKm9iXZeXYyuD0NSWPmvuchQzuPCOqu+qOxbNQ7usCeol/wbycd4D1WJrY5URqWVR2+NGBB9ZoO4W+eE9Y2K+qv152flQMZ+uQclp2xXxmm9yD10Ndm9s4a75jai+fPJhOe7sS2nZbOjnskK2sTl1deI=
